import sys
import os
import datetime
import sqlite3
sys.path.append(os.path.join(os.getcwd(), 'backend'))

from app.core.database import SessionLocal
from app.models.reading import Reading

db = SessionLocal()

print("--- PHASE 1 B: Identify the creator of IDs 364-374 ---")
readings_b = db.query(Reading).filter(Reading.id >= 364, Reading.id <= 374).all()
for r in readings_b:
    # We saw earlier: ID 364 is physical_sensor, 365-374 is weather_api (some TEST, some REAL)
    # wait, the list is exactly 364 to 374.
    if r.id == 364:
        creator = "poll_stations() / ingestion_service.py"
        evidence = "Has physical_sensor source, perfectly matches poll interval, but was caught between API runs."
        c = "CERTAIN_REAL"
    elif r.timestamp >= datetime.datetime.fromisoformat('2026-09-28T15:00:00'):
        creator = "mock_poll.py or similar test loop script"
        evidence = "Timestamp is strictly in the future (>= 15:00 UTC) which was generated by a mock script injecting future times."
        c = "CERTAIN_TEST"
    else:
        creator = "poll_stations() via background Uvicorn/scheduler or live_poll.py"
        evidence = "Has weather_api source, timestamp is chronological with current real time (before 15:00), no mock script injected these specific timestamps in the past."
        c = "CERTAIN_REAL"

    print(f"{r.id} | {r.station_id} | {r.timestamp} | {r.source.name} | T:{r.temperature:.1f}/P:{r.pressure:.1f}/H:{r.humidity:.1f} | {creator} | {evidence} | {c}")

print("\n--- PHASE 1 C: Full reading provenance (340 to max) ---")
readings_c = db.query(Reading).filter(Reading.id >= 340).all()

for r in readings_c:
    if r.station_id == 'AWS-001':
        c = "DO_NOT_TOUCH_AWS001"
        ev = "AWS-001 is off limits per strict rules."
    elif r.timestamp >= datetime.datetime.fromisoformat('2026-09-28T15:00:00'):
        c = "CERTAIN_TEST"
        ev = "Future timestamp (>= 15:00 UTC) injected by a test script."
    elif r.id in range(348, 364):
        c = "CERTAIN_TEST"
        ev = "Known test ID range from mock injection script (e.g., test_cases.py)."
    elif r.id >= 364 and r.id <= 374:
        if r.timestamp >= datetime.datetime.fromisoformat('2026-09-28T15:00:00'):
            c = "CERTAIN_TEST"
            ev = "Future timestamp injected by mock_poll.py."
        else:
            c = "CERTAIN_REAL"
            ev = "Genuine background poll before 15:00 UTC."
    else:
        c = "CERTAIN_REAL"
        ev = "Chronological timestamp < 15:00 UTC with no evidence of mock injection."

    print(f"{r.id} | {r.station_id} | {r.timestamp} | {r.source.name} | {r.temperature:.1f} | {r.pressure:.1f} | {r.humidity:.1f} | {c} | {ev}")

